version: "3.0"

services:
  # node:
  #   image: node:14
  #   command: npm run watch
  #   volumes:
  #       - .:/app
  #   working_dir: /app    

  # test-mysql:
  #   image: node:14
  #   command: 'npm run test:watch:mysql'
  #   volumes:
  #       - .:/app
  #   working_dir: /app
  #   environment:
  #     CONN: mysql://supersave:savesuper@mysql/supersave
  #     #DEBUG: supersave:*
  #   links:
  #     - mysql

  # test-sqlite:
  #   image: node:14
  #   command: npm run test:watch
  #   volumes:
  #       - .:/app
  #   working_dir: /app
  #   environment:
  #     CONN: 'sqlite://:memory:'
  #     #DEBUG: supersave:*

  mysql:
    image: mysql:8.4
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=supersave
      - MYSQL_USER=supersave
      - MYSQL_PASSWORD=savesuper
      - MYSQL_RANDOM_ROOT_PASSWORD=1

  mariadb:
    image: mariadb:11.8
    ports:
        - 3307:3306
    environment:
      - MARIADB_DATABASE=supersave
      - MARIADB_USER=supersave
      - MARIADB_PASSWORD=savesuper
      - MARIADB_RANDOM_ROOT_PASSWORD=1